---
apiVersion: v1
kind: Service
metadata:
  name: external-scaler
  namespace: kruise-game-system
spec:
  ports:
    - port: 6000
      targetPort: 6000
  selector:
    control-plane: controller-manager